apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: adithya180498
    provider: https://github.com
    providerKind: github
    repositories:
    - name: golang
    - name: golang-http123
    - name: jenkins-cwp-quickstart
    - name: jenkins-quickstart
    - name: jx3
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
